# Generated by Django 5.1.1 on 2024-09-25 09:05

import django.db.models.deletion
from django.db import migrations, models

from app_list.models import OrganizationApp


def create_shopify_app(apps, schema_editor):
    App = apps.get_model('app_list', 'App')
    App.objects.create(name='shopify', description='Shopify app')

def create_shopify_org(apps, schema_editor):
    App = apps.get_model('app_list', 'App')
    app = App.objects.get(name='shopify')
    OrganizationApp.objects.create(app_id=app.id, organization_id='1', app_specific_params={'store_name': 'gym-wala-store', 'auth_token': 'xyz'})

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_list", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_shopify_app, migrations.RunPython.noop),
        migrations.RunPython(create_shopify_org)]