# Generated by Django 5.1.1 on 2024-09-25 09:05

import django.db.models.deletion
from django.db import migrations, models

from app_list.models import OrganizationApp


def create_bigcommerce_app(apps, schema_editor):
    App = apps.get_model('app_list', 'App')
    App.objects.create(name='bigcommerce', description='Shopify app')

def create_bigcommerce_org(apps, schema_editor):
    App = apps.get_model('app_list', 'App')
    app = App.objects.get(name='bigommerce')
    OrganizationApp.objects.create(app_id=app.id, organization_id='1', app_specific_params={'store_name': 'gym-wala-store', 'auth_token': 'xyz'})

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_list", "0002_create_shopify"),
    ]

    operations = [
        migrations.RunPython(create_bigcommerce_app, migrations.RunPython.noop),
        migrations.RunPython(create_bigcommerce_org, migrations.RunPython.noop)]